// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Demo = require("./demo.js");

var result = Demo.Int.mul(2, 3);

console.log("Result:", result);

exports.result = result;
/* result Not a pure module */
